# Generated by Django 4.1.2 on 2022-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True, verbose_name='Event name')),
                ('status', models.CharField(choices=[('s', 'Comming Up'), ('i', 'In Progress'), ('d', 'Event Finished')], max_length=1, verbose_name='Event state')),
            ],
        ),
    ]
